<h1 style="color:cornflowerblue">Studying Numpy for Data Science</h1>
<p>For this class, some lines of coding are here just for remembering the basics. Also, this are some Advantages of using Numpy</p>

<h2 style="color:cornflowerblue">Pros: Operators</h2>

In [1]:
# Importing Numpy Library
import numpy as np

# Other Libraries
import time

In [2]:
regular_list = [1, 2, 3]

In [3]:
type(regular_list)

list

In [4]:
regular_list * 2

[1, 2, 3, 1, 2, 3]

In [5]:
[number + 2 for number in regular_list]

[3, 4, 5]

In [6]:
[number * 2 for number in regular_list]

[2, 4, 6]

In [7]:
regular_list_2 = [4, 5, 6]

In [8]:
regular_list + regular_list_2

[1, 2, 3, 4, 5, 6]

In [9]:
list_as_np_array = np.array([1, 2, 3])
list_as_np_array

array([1, 2, 3])

In [10]:
type(list_as_np_array)

numpy.ndarray

In [11]:
list_as_np_array*2

array([2, 4, 6])

In [12]:
list_as_np_array_2 = np.array([4, 5, 6])
list_as_np_array_2

array([4, 5, 6])

In [13]:
list_as_np_array + list_as_np_array_2

array([5, 7, 9])

In [14]:
list_as_np_array - list_as_np_array_2

array([-3, -3, -3])

<h2 style="color:cornflowerblue">Pros: Speed</h2>

In [15]:
size = int(2e8)

In [16]:
%%time

biglist = range(size)

CPU times: total: 0 ns
Wall time: 0 ns


In [17]:
%%time

bigarray = np.arange(size)

CPU times: total: 172 ms
Wall time: 173 ms


In [18]:
%%time

biglist_2 = [number+2 for number in biglist]

CPU times: total: 9.73 s
Wall time: 10.9 s


In [19]:
%%time

bigarray += 2

CPU times: total: 141 ms
Wall time: 157 ms


<h2 style="color:cornflowerblue">Basic Characteristics</h2>

In [20]:
info_array = np.array([1,2,3])
info_array

array([1, 2, 3])

In [21]:
info_array.ndim

1

In [22]:
info_array.shape

(3,)

In [23]:
info_array_2d = np.array([[1, 2, 3],[4, 5, 6]])
info_array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
info_array_2d.ndim

2

In [25]:
info_array_2d.shape

(2, 3)

In [26]:
info_array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
info_array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
info_array_3d.ndim

3

In [28]:
info_array_3d.shape

(2, 2, 2)

<h2 style="color:cornflowerblue">Types</h2>

In [41]:
a = np.array([1, 2, 3])
print(a.dtype)
print(a.nbytes)

int32
12


In [42]:
b = np.array([1, 2, 3.])
print(b.dtype)
print(b.nbytes)

float64
24


In [43]:
c = np.array(["1", 2, 3.])
print(c.dtype)
print(c.dtype.name)
print(c.nbytes)

<U32
str1024
384


In [44]:
b = b.astype("float32")
print(b.dtype)
print(b.nbytes)

float32
12


In [45]:
a = np.arange(100)
print(a.dtype)
print(a.nbytes)

int32
400


In [46]:
a = a.astype("int8")
print(a.dtype)
print(a.nbytes)

int8
100


<h2 style="color:cornflowerblue">Data Generation</h2>

In [47]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.random.random((3,4))

array([[0.10457402, 0.70737649, 0.40916252, 0.55567563],
       [0.7453968 , 0.94511121, 0.25270793, 0.40670973],
       [0.67947347, 0.02543217, 0.11387321, 0.09799438]])

In [51]:
np.random.randint(1,30,50)

array([ 6, 13, 24, 23,  5, 16, 20,  7,  8, 24,  7, 10, 16, 14, 14,  6,  2,
        6, 15, 27, 13, 11, 27, 25,  2, 28,  5, 23, 11, 17,  7,  2, 12,  3,
        9,  6,  2, 11, 12, 22, 25, 19,  1, 10, 21, 13,  6, 13,  4, 24])

In [52]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
"Conitinue at 30"