<h1 style="color:cornflowerblue">Studying Numpy for Data Science</h1>
<p>For this class, some lines of coding are here just for remembering the basics. Also, this are some Advantages of using Numpy</p>

<h2 style="color:cornflowerblue">Pros: Operators</h2>

In [17]:
# Importing Numpy Library
import numpy as np

# Other Libraries
import time

In [2]:
regular_list = [1, 2, 3]

In [3]:
type(regular_list)

list

In [4]:
regular_list * 2

[1, 2, 3, 1, 2, 3]

In [6]:
[number + 2 for number in regular_list]

[3, 4, 5]

In [7]:
[number * 2 for number in regular_list]

[2, 4, 6]

In [8]:
regular_list_2 = [4, 5, 6]

In [9]:
regular_list + regular_list_2

[1, 2, 3, 4, 5, 6]

In [11]:
list_as_np_array = np.array([1, 2, 3])
list_as_np_array

array([1, 2, 3])

In [12]:
type(list_as_np_array)

numpy.ndarray

In [13]:
list_as_np_array*2

array([2, 4, 6])

In [14]:
list_as_np_array_2 = np.array([4, 5, 6])
list_as_np_array_2

array([4, 5, 6])

In [15]:
list_as_np_array + list_as_np_array_2

array([5, 7, 9])

In [16]:
list_as_np_array - list_as_np_array_2

array([-3, -3, -3])

<h2 style="color:cornflowerblue">Pros: Speed</h2>

In [19]:
size = int(2e8)
biglist = range(size)

In [23]:
%%time

biglist_2 = [number+2 for number in range(size)]

CPU times: total: 12.7 s
Wall time: 16.2 s


In [27]:
bigarray = np.arange(size)

In [25]:
%%time

bigarray_2 = [number+2 for number in range(size)]

CPU times: total: 10.2 s
Wall time: 17.3 s


In [29]:
%%time

bigarray_2 += 2

TypeError: 'int' object is not iterable